### ISSUE TITLE
Using postcss + autoprefixer alongside sass plugin

### ISSUE THREAD

**Issue by jcfranco** [ionic-team/stencil-postcss#17]
Maybe I'm missing something, but I don't notice any difference in output in a project that has both `@stencil/sass` and `@stencil/postcss` plugins. 

Here's my config:

```ts
// stencil.config.ts

import { Config } from "@stencil/core";
import { postcss } from "@stencil/postcss";
import { sass } from "@stencil/sass";
import autoprefixer from "autoprefixer";

export const config: Config = {
  namespace: "repro",
  bundles: [
    {
      components: [
        // ...
      ]
    }
  ],
  outputTargets: [
    { type: "dist" },
    {
      type: "www",
      serviceWorker: null // disable service workers
    }
  ],
  globalStyle: "src/assets/styles/global.scss",
  plugins: [
    sass({
      injectGlobalPaths: ["src/assets/styles/global.scss"]
    }),

    (postcss as any)({
      plugins: [autoprefixer()]
    })
  ]
};
```

and my `.browserslistrc` looks like so:

```rc
# Browsers that we support
last 2 chrome versions
last 2 edge versions
last 2 ff versions
last 2 safari versions
last 2 ios versions
ie 11
```

I am not seeing any difference in the CSS that's inlined in the built components **with and without PostCSS + Autoprefixer**. 

**test class**

```scss
  :host .test {
    display: grid;
    transition: all .5s;
    user-select: none;
    background: linear-gradient(to bottom, white, black);
  }
```

**same output with and without PostCSS + Autoprefixer (formatted for readability)**

```css
  :host .test {
    display: grid;
    -webkit-transition: all .5s;
    transition: all .5s;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    background: -webkit-gradient(linear, left top, left bottom, from(#fff), to(#000));
    background: linear-gradient(180deg, #fff, #000)
  }
```

If you use the test class in the [Autoprefixer playground](https://autoprefixer.github.io/), and set the filter to `last 2 chrome versions, last 2 edge versions, last 2 ff versions, last 2 safari versions, last 2 ios versions, ie 11`, you get the following:

**expected**

```scss
  :host .test {
    display: -ms-grid;
    display: grid;
    transition: all .5s;
    -webkit-user-select: none;
       -moz-user-select: none;
        -ms-user-select: none;
            user-select: none;
    background: linear-gradient(to bottom, white, black);
  }
```

**Comment by Jefiozie** [comment]
Maybe I'm missing some context here but did you expect to see different? 😄

**Comment by jcfranco** [comment]
Yes, I've updated the description with info on the expected result.

**Comment by Jefiozie** [comment]
Could you share the versions of `@stencil` for me? I'm trying to reproduce the issue but I don't have the problems you are facing. thanks 🙏🏻

**Comment by jcfranco** [comment]
These are our latest stencil deps: `@stencil/core@1.1.3`, `@stencil/postcss@1.0.1`, and `@stencil/sass@1.0.1`. Now, there's only a minor difference in the generated CSS:

```css
:host .test {
  /* missing -> display: -ms-grid; */
  display: grid;
  transition: all 0.5s;
  -webkit-user-select: none;
     -moz-user-select: none;
      -ms-user-select: none;
          user-select: none;
  background: linear-gradient(to bottom, white, black);
}
```

FWIW, I wasn't able to reproduce the original issue using our previous deps: `@stencil/core@one`, `@stencil/postcss@0.1.0`, and `@stencil/sass@0.2.3`. Probably something wrong with my setup.
